import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Sprint 1 tables of the identity_access schema. Generated by TypeORM from the
 * ORM entities (pnpm migration:generate:*), plus the schema creation.
 */
export class InitialIdentityAccessSchema1791296250262 implements MigrationInterface {
  name = 'InitialIdentityAccessSchema1791296250262';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS "identity_access"`);
    await queryRunner.query(
      `CREATE TABLE "identity_access"."users" ("id" uuid NOT NULL, "email" character varying(320) NOT NULL, "password_hash" character varying(255) NOT NULL, "role" character varying(32) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // The schema is kept: it also holds this context's migrations table.
    await queryRunner.query(`DROP TABLE "identity_access"."users"`);
  }
}
