import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Sprint 1 tables of the alerting schema. Generated by TypeORM from the
 * ORM entities (pnpm migration:generate:*), plus the schema creation.
 */
export class InitialAlertingSchema1791296254937 implements MigrationInterface {
  name = 'InitialAlertingSchema1791296254937';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS "alerting"`);
    await queryRunner.query(
      `CREATE TABLE "alerting"."alert_rules" ("id" uuid NOT NULL, "name" character varying(120) NOT NULL, "threshold_kwh" double precision NOT NULL, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_ae580564f087ffab9d229225aec" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "alerting"."alerts" ("id" uuid NOT NULL, "rule_id" uuid NOT NULL, "device_id" character varying(100) NOT NULL, "consumption_kwh" double precision NOT NULL, "message" character varying(500) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_60f895662df096bfcdfab7f4b96" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_a03c8afb3e29b85c8feccd730e" ON "alerting"."alerts"  ("rule_id") `,
    );
    await queryRunner.query(
      `ALTER TABLE "alerting"."alerts" ADD CONSTRAINT "FK_a03c8afb3e29b85c8feccd730ef" FOREIGN KEY ("rule_id") REFERENCES "alerting"."alert_rules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // The schema is kept: it also holds this context's migrations table.
    await queryRunner.query(
      `ALTER TABLE "alerting"."alerts" DROP CONSTRAINT "FK_a03c8afb3e29b85c8feccd730ef"`,
    );
    await queryRunner.query(
      `DROP INDEX "alerting"."IDX_a03c8afb3e29b85c8feccd730e"`,
    );
    await queryRunner.query(`DROP TABLE "alerting"."alerts"`);
    await queryRunner.query(`DROP TABLE "alerting"."alert_rules"`);
  }
}
