import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Sprint 1 tables of the energy_monitoring schema. Generated by TypeORM from the
 * ORM entities (pnpm migration:generate:*), plus the schema creation.
 */
export class InitialEnergyMonitoringSchema1791296252925 implements MigrationInterface {
  name = 'InitialEnergyMonitoringSchema1791296252925';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS "energy_monitoring"`);
    await queryRunner.query(
      `CREATE TABLE "energy_monitoring"."energy_measurements" ("id" uuid NOT NULL, "device_id" character varying(100) NOT NULL, "consumption_kwh" double precision NOT NULL, "measured_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_84cffb729a6964180ceac0aebc6" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_a24c9fece01e85cdb3699c8a52" ON "energy_monitoring"."energy_measurements"  ("device_id") `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // The schema is kept: it also holds this context's migrations table.
    await queryRunner.query(
      `DROP INDEX "energy_monitoring"."IDX_a24c9fece01e85cdb3699c8a52"`,
    );
    await queryRunner.query(
      `DROP TABLE "energy_monitoring"."energy_measurements"`,
    );
  }
}
