# Bounded Context: Energy Monitoring (apps/energy-monitoring-service)
# Entry point: API Gateway (http://localhost:3000/api/v1)
# Automated coverage: apps/energy-monitoring-service/src/**/*.spec.ts
@sprint-1 @energy-monitoring
Feature: Energy Monitoring
  As a SmartEnergy user
  I want to record and review my energy measurements
  So that I can understand how much energy my devices consume

  Background:
    Given the API Gateway is running

  Scenario: Register an energy measurement
    When the client sends "POST /measurements" with:
      | deviceId   | consumptionKwh | measuredAt               |
      | device-001 | 3.75           | 2026-10-06T10:30:00.000Z |
    Then the response status is 201
    And the response contains an "id" generated by the backend
    And the measurement is stored with the consumption 3.75 kWh

  Scenario: Reject an invalid energy measurement
    When the client sends "POST /measurements" with a negative "consumptionKwh"
    Then the response status is 400

  Scenario: Retrieve energy measurements
    Given these stored energy measurements:
      | deviceId   | consumptionKwh | measuredAt               |
      | device-001 | 3.75           | 2026-10-06T10:30:00.000Z |
      | device-002 | 6.25           | 2026-10-06T11:00:00.000Z |
    When the client sends "GET /measurements"
    Then the response status is 200
    And the response contains 2 measurements, the most recent first

  Scenario: Filter energy measurements by device
    Given stored energy measurements of "device-001" and "device-002"
    When the client sends "GET /measurements?deviceId=device-001"
    Then the response only contains measurements of "device-001"

  Scenario: Retrieve an energy measurement by id
    Given a stored energy measurement
    When the client sends "GET /measurements/:id" with its id
    Then the response status is 200
    And the response contains that measurement

  Scenario: Retrieve an unknown energy measurement
    When the client sends "GET /measurements/00000000-0000-4000-8000-000000000000"
    Then the response status is 404

  Scenario: Obtain consumption summary
    Given these stored energy measurements:
      | deviceId   | consumptionKwh |
      | device-001 | 3.75           |
      | device-001 | 4.25           |
      | device-002 | 2.50           |
      | device-002 | 6.00           |
      | device-003 | 4.00           |
    When the client sends "GET /measurements/summary"
    Then the response status is 200
    And the "totalMeasurements" is 5
    And the "totalConsumptionKwh" is 20.5
    And the "averageConsumptionKwh" is 4.1
